<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    const TYPE = array(
        'NULL' => 0,
        'XBXZCF' => 1,
        'XBXZXK' => 2,
        'QYYCMLXX' => 3,
        'SXQYHMD' => 4,
        'DYZGXX' => 5,
        'QYGDZCTZXMHZHBA' => 6,
        'ZFCGDLJGXX' => 7,
        'QYGSZXXX' => 8,
        'AJNSRXX' => 9,
        'QYDSXZCFXX' => 10,
        'YSCRJZJJJZGRDXX' => 11,
        'SFJDJGCYRYZGXX' => 12,
        'QXTCHJBHJDXX' => 13,
        'PXSTYXHDJXX' => 14,
        'HSZYZGZXX' => 15,
        'JGJCDXZJL' => 16,
        'JXSZLJDW' => 17,
        'ZLJCQYXX' => 18,
        'SLGCZBXX' => 19,
        'ESCJDPGJGHZZS' => 20,
        'PGJGXX' => 21,
        'DTJXJGRXX' => 22,
        'YXZZDWJBGXX' => 23,
        'SLYSXKZXX' => 24,
        'ZYJNZSXX' => 25,
        'QYRYXX' => 26,
        'SHZZNJXX' => 27,
        'YLBXXX' => 28,
        'TJDCDXML' => 29,
        'JDCWFXX' => 30,
        'GTGSHXX' => 31,
        'CMQYSBXX' => 32,
        'YPLSQYXX' => 33,
        'YZTQSBXXHMD' => 34,
        'JGRYXX' => 35,
        'SPYPTSJBJLGR' => 36,
        'SPYPTSJBJLDW' => 37,
        'JXMPCPXX' => 38,
        'JSZGXX' => 39,
        'SJYXXS' => 40,
        'SYBXXX' => 41,
        'SJJXMXX' => 42,
        'JYJGXINXI' => 43,
        'GRRYXXJYJ' => 44,
        'GRRYXXJTJ' => 45,
        'GRRYXXGDJ' => 46,
        'GRRYXXMZJ' => 47,
        'SBQYXX' => 48,
        'SFJDJGDJXX' => 49,
        'GZJGJBXX' => 50,
        'GZYXX' => 51,
        'JCFLFWSXX' => 52,
        'JCFLFWGZZJBXX' => 53,
        'LSSWSXX' => 54,
        'LSZYZGZXX' => 55,
        'GZRYXX' => 56,
        'YSZYZCHBGZC' => 57,
        'YSZYZGZXX' => 58,
        'WSHJHSYWYHJCXX' => 59,
        'YLHJSFWJGXX' => 60,
        'JBYFKZJGXX' => 61,
        'FYCRYJLXX' => 62,
        'WSZYJSZGKSWJXX' => 63,
        'QSWCXXXJDWBZ' => 64,
        'YZTQNMGGZHMD' => 65,
        'JGRYXXSWGXJ' => 66,
        'JGRYXXSJYJ' => 67,
        'JGRYXXSSFJ' => 68,
        'MBFQYML' => 69,
        'SHTTDJXX' => 70,
        'QYZXXX' => 71,
        'QYDXXX' => 72,
        'CCJCJGXX' => 73,
        'TZXMBLJGGSXX' => 74,
        'TZXMMCDMPPXX' => 75,
        'SFJDRXX' => 76,
        'SFJDJGXX' => 77,
        'LSZYXX' => 78,
        'LSNDPJXX' => 79,
        'LSSWSNDPJXX' => 80,
        'SAJLVJQ' => 81,
        'BWGXX' => 82,
        'WWSDXX' => 83,
        'WWSDGMXSJLSX' => 84,
        'QYSWJBDJXX' => 85,
        'NSXYDJPDXX' => 86,
        'QYQSGGXX' => 87,
        'FZCNSRXX'=> 88,
        'LXSDJXX' => 89,
        'GRYCJJBAXX' => 90,
        'XZJLXXZRR' => 91,
        'XZJLXXFRHQTZZ' => 92,
        'MZSHTTHMBFQYDW' => 93,
        'QYJBXX' => 94,
        'SXBZXRXX' => 95,
        'ZDSSWFAJXX' => 96,
        'HXLDGXXX' => 97,
        'SCAQBLJLHMD' => 98,
        'YZSXWFQY' => 99,
        'HGSXQY' => 100,
        'HGGJRZ' => 101,
        'ZZQSGBZHSFGDMD' => 102,
        'ZZQCYBGCZLJMD' => 103,
        'ZZQYZYBGCMD' => 104,
        'SLJSSC' => 105,
        'LHCJFRHMD'=>106,
        'LHJLFRHMD'=>107,
        'XYSFSQ'=>108,
        'C_AJASRMD'=>109,
        'C_AJNSR'=>110,
        'C_SXBZXJG'=>111,
        'P_VWEB_PERSON'=>112,
        'C_JYZCX'=>113,
        'C_NYLYJL'=>114,
        'C_SBHQJT'=>115,
        'DDMFSBHR'=>116,
        'NYLYGRJLXX'=>117,
        'P_JGJGBB'=>118,
        'P_SXBZXR'=>119,
        'P_YXSBHQS'=>120,
        'C_DKJBXX'=>121,
        'C_DSSWDJXX'=>122,
        'C_ZFGJJ'=>123,
        'DFJFJL_INFO'=>124,
        'P_GJJDKXX'=>125,
        'P_GRDBJFF_INFO'=>126,
        'P_SFQJXX'=>127,
        'P_SJYJT_XSXJXX'=>128,
        'P_VWEB_LOAN_INFO'=>129,
        'P_WATER_INFO'=>130,
        'C_ESFBA'=>131,
        'P_FDDBR'=>132,
        'DFXBMDXX'=>133,
        'DFXRMDXX'=>134,
        'DFXYF'=>135,
        'GJJGRDKXX'=>136,
        'GJJGRJCXX'=>137,
        'NSXX'=>138,
        'QSXX'=>139,
        'RYJLXX'=>140,
        'ZRRGYSYJFXX'=>141,
        'ZRRTQGYSYFXX'=>142,
        'GJJJCXX'=>143,
        'FRGYSYJFXX'=>144,
        'FRHEIMD'=>145,
        'FRHONGMD'=>146,
        'FRNSXX'=>147,
        'FRQSXX'=>148,
        'FRTQGYSYFXX'=>149,
        'RYBZXX'=>150,
        'CCWLJJLXX'=>151,
        'CCWLYQXX'=>152,
        'FRYDJFXX'=>153,
        'FRYDTQFXX'=>154,
        'FRYQJFXX'=>155,
        'FRYQTQFXX'=>156,
        'FRYSJFXX'=>157,
        'FRYSTQFXX'=>158,
        'ZRRYDJFXX'=>159,
        'ZRRYDTQFXX'=>160,
        'ZRRYQJFXX'=>161,
        'ZRRYQTQFXX'=>162,
        'ZRRYSJFXX'=>163,
        'ZRRYSTQFXX'=>164,
        'C_TJLYQYJB'=>165,
        'C_YYCL'=>166,
        'P_CAR_INFO'=>167,
        'P_DZDY_INFO'=>168,
        'P_GET_BZXZF'=>169,
        'P_HSZYZ'=>170,
        'P_TEZYRY'=>171,
        'C_AQSCBZHQY'=>172,
        'C_CHZZDW'=>173,
        'C_CKXKZ'=>174,
        'C_GXJSQYRD'=>175,
        'C_JYJG'=>176,
        'P_EJTYZDY_INFO'=>177,
        'P_EJYDY_INFO'=>178,
        'C_MBFQY_INFO'=>179,
        'C_MBFQYDWNJ'=>180,
        'C_SHTTNJ_INFO'=>181,
        'P_GRHYDJ_INFO'=>182,
        'C_QXZHFYZDDW'=>183,
        'C_QYDSJBDJ'=>184,
        'C_SSZDWFAJ'=>185,
        'C_QYDX_INFO'=>186,
        'C_QYGDTZZ_INFO'=>187,
        'C_QYYCML_INFO'=>188,
        'C_YLQXJYQY'=>189,
        'P_ZRRGD_INFO'=>190,
        'C_SFJFJL'=>191,
        'C_SYDWNDBG'=>192,
        'C_SYDW_INFO'=>193,
        'C_YYCB'=>194,
        'DLSZYZZJL_INFO'=>195,
        'FLFWGZZ_INFO'=>196,
        'LSZYZG_INFO'=>197,
        'SFJDCYRY_INFO'=>198,
        'LDBZNDSMSC_INFO'=>199,
        'LDYG_INFO'=>200,
        'P_JZHJCWFJL'=>201,
        'P_YSZYZ'=>202,
        'WMDW_INFO'=>203,
        'GRDKHKMX'=>204,
        'GRJCJCXX'=>205,
        'GRJCMX'=>206,
        'GRMXXX'=>207,
        'JASRKJBXX'=>208,
        'C_GTZYLYRY'=>209,
        'C_HBHMDQY'=>210,
        'P_GRHBRYXX'=>211,
        'C_JGJGXJJT'=>212,
        'P_JGWMG'=>213,
        'C_JGRY'=>214,
        'C_JGRYXX'=>215,
        'C_JXQNWSJ'=>216,
        'C_QNWMH'=>217,
        'C_QSYXSXDJT'=>218,
        'C_YXQNZYZ'=>219,
        'P_HLJJJY'=>220,
        'P_JASDJCQN'=>221,
        'P_QSYXGQTY'=>222,
        'P_QSYXGQY'=>223,
        'P_QSYXSXDFDY'=>224,
        'P_QSYXSXDY'=>225,
        'P_SDJCQNTM'=>226,
        'P_WSJ'=>227,
        'P_YXQN'=>228,
        'C_QSJYXTXJJT'=>229,
        'P_GUA_GZZ_INFO'=>230,
        'DGZJGJL_INFO'=>231,
        'DLSSWSJL_INFO'=>232,
        'DSFJDJGJL_INFO'=>233,
        //@position_type_234
        'TEST' => 500,
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
            self::TYPE['DFXRMDXX'],
            self::TYPE['DFXYF'],
            self::TYPE['RYJLXX'],
            self::TYPE['FRHONGMD'],
            self::TYPE['RYBZXX']
        ),
        IUserGroup::ID['SFGW'] => array(self::TYPE['ZRRYSTQFXX'],self::TYPE['ZRRYSJFXX'],self::TYPE['ZRRYQTQFXX'],self::TYPE['ZRRYQJFXX'],self::TYPE['ZRRYDTQFXX'],self::TYPE['ZRRYDJFXX'],self::TYPE['FRYSTQFXX'],self::TYPE['FRYSJFXX'],self::TYPE['FRYQTQFXX'],self::TYPE['FRYQJFXX'],self::TYPE['FRYDTQFXX'],self::TYPE['FRYDJFXX'],self::TYPE['CCWLYQXX'],self::TYPE['CCWLJJLXX'],self::TYPE['FRTQGYSYFXX'],self::TYPE['FRQSXX'],self::TYPE['FRNSXX'],self::TYPE['FRHEIMD'],self::TYPE['FRGYSYJFXX'],self::TYPE['GJJJCXX'],self::TYPE['ZRRTQGYSYFXX'],self::TYPE['ZRRGYSYJFXX'],self::TYPE['QSXX'],self::TYPE['NSXX'],self::TYPE['GJJGRJCXX'],self::TYPE['GJJGRDKXX'],self::TYPE['DFXBMDXX'],
            self::TYPE['LHJLFRHMD'],
            self::TYPE['LHCJFRHMD'],
            self::TYPE['JGJCDXZJL'],
            self::TYPE['SJJXMXX'],
            self::TYPE['TZXMBLJGGSXX'],
            self::TYPE['TZXMMCDMPPXX'],
            self::TYPE['QYGDZCTZXMHZHBA'],
            self::TYPE['TEST'],
        ),
        IUserGroup::ID['SZFB'] => array(),
        IUserGroup::ID['SRMYH'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SSCJDGLJ'] => array(
            self::TYPE['P_FDDBR'],
            self::TYPE['QYJBXX'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['SXQYHMD'],
            self::TYPE['GTGSHXX'],
            self::TYPE['CMQYSBXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'],
            self::TYPE['YPLSQYXX'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
            self::TYPE['JGRYXX'],
            self::TYPE['SCAQBLJLHMD'],
            self::TYPE['YZSXWFQY'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_QYDX_INFO'],
            self::TYPE['C_QYGDTZZ_INFO'],
            self::TYPE['C_QYYCML_INFO'],
            self::TYPE['C_YLQXJYQY'],
            self::TYPE['P_ZRRGD_INFO'],
        ),
        IUserGroup::ID['SSWJ'] => array(
            self::TYPE['C_DSSWDJXX'],
            self::TYPE['C_AJNSR'],
            self::TYPE['C_AJASRMD'],
            self::TYPE['QYGSZXXX'],
            self::TYPE['AJNSRXX'],
            self::TYPE['QYDSXZCFXX'],
            self::TYPE['QYSWJBDJXX'],
            self::TYPE['NSXYDJPDXX'],
            self::TYPE['QYQSGGXX'],
            self::TYPE['FZCNSRXX'],
            self::TYPE['ZDSSWFAJXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX'],
            self::TYPE['C_QYDSJBDJ'],
            self::TYPE['C_SSZDWFAJ'],
        ),
        IUserGroup::ID['SRSJ'] => array(
            self::TYPE['ZYJNZSXX'],
            self::TYPE['YLBXXX'],
            self::TYPE['YZTQSBXXHMD'],
            self::TYPE['SYBXXX'],
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD'],
            self::TYPE['HXLDGXXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['LDBZNDSMSC_INFO'],
            self::TYPE['LDYG_INFO'],
        ),
        IUserGroup::ID['SHBJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_HBHMDQY'],
            self::TYPE['P_GRHBRYXX']
        ),
        IUserGroup::ID['SFY'] => array(
            self::TYPE['P_SXBZXR'],
            self::TYPE['C_SXBZXJG'],
            self::TYPE['SXBZXRXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SJTJ'] => array(self::TYPE['P_CAR_INFO'],self::TYPE['C_YYCL'],
            self::TYPE['SLYSXKZXX'],
            self::TYPE['GRRYXXJTJ'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_YYCB'],
        ),
        IUserGroup::ID['SWJ'] => array(
            self::TYPE['ESCJDPGJGHZZS'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SJCY'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SYBJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SGYHXXHJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SYJGLJ'] => array(self::TYPE['P_TEZYRY'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_AQSCBZHQY'],
            self::TYPE['C_JGRY']
        ),
        IUserGroup::ID['SZRZYJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_CHZZDW'],
            self::TYPE['C_CKXKZ'],
            self::TYPE['C_GTZYLYRY'],
        ),
        IUserGroup::ID['SGAJ'] => array(
            self::TYPE['YSCRJZJJJZGRDXX'],
            self::TYPE['JDCWFXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['P_JZHJCWFJL'],
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['SJYJ'] => array(
            self::TYPE['P_SJYJT_XSXJXX'],
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_JYJG'],
            self::TYPE['P_EJTYZDY_INFO'],
            self::TYPE['P_EJYDY_INFO'],
            self::TYPE['C_QSJYXTXJJT'],
            self::TYPE['P_GUA_GZZ_INFO'],
        ),
        IUserGroup::ID['SWSJKW'] => array(self::TYPE['P_HSZYZ'],
            self::TYPE['HSZYZGZXX'],
            self::TYPE['YSZYZCHBGZC'],
            self::TYPE['YSZYZGZXX'],
            self::TYPE['WSHJHSYWYHJCXX'],
            self::TYPE['YLHJSFWJGXX'],
            self::TYPE['JBYFKZJGXX'],
            self::TYPE['FYCRYJLXX'],
            self::TYPE['WSZYJSZGKSWJXX'],
            self::TYPE['QSWCXXXJDWBZ'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['P_YSZYZ']
        ),
        IUserGroup::ID['SJRB'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']            
        ),
        IUserGroup::ID['SNMJ'] => array(
            self::TYPE['NYLYGRJLXX'],
            self::TYPE['C_NYLYJL'],
            self::TYPE['C_JYZCX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SZWFWJ'] => array(),
        IUserGroup::ID['STJJ'] => array(self::TYPE['C_TJLYQYJB'],
            self::TYPE['DTJXJGRXX'],
            self::TYPE['TJDCDXML'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SKJJ'] => array(
            self::TYPE['JXSZLJDW'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_GXJSQYRD'],
            self::TYPE['C_JGRYXX'],
        ),
        IUserGroup::ID['SMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO'],
            self::TYPE['MZSHTTHMBFQYDW'],
            self::TYPE['SHZZNJXX'],
            self::TYPE['GRRYXXMZJ'],
            self::TYPE['MBFQYML'],
            self::TYPE['SHTTDJXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_MBFQY_INFO'],
            self::TYPE['C_MBFQYDWNJ'],
            self::TYPE['C_SHTTNJ_INFO'],
            self::TYPE['P_GRHYDJ_INFO'],
        ),
        IUserGroup::ID['SSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ'],
            self::TYPE['SFJDRXX'],
            self::TYPE['SFJDJGXX'],
            self::TYPE['LSZYXX'],
            self::TYPE['LSNDPJXX'],
            self::TYPE['LSSWSNDPJXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['DLSZYZZJL_INFO'],
            self::TYPE['FLFWGZZ_INFO'],
            self::TYPE['LSZYZG_INFO'],
            self::TYPE['SFJDCYRY_INFO'],
            self::TYPE['DGZJGJL_INFO'],
            self::TYPE['DLSSWSJL_INFO'],
            self::TYPE['DSFJDJGJL_INFO'],
        ),
        IUserGroup::ID['SZJJ'] => array(self::TYPE['P_GET_BZXZF'],self::TYPE['C_ESFBA'],
            self::TYPE['P_VWEB_PERSON'],
            self::TYPE['ZLJCQYXX'],
            self::TYPE['JXMPCPXX'],
            self::TYPE['CCJCJGXX'],
            self::TYPE['ZZQSGBZHSFGDMD'],
            self::TYPE['ZZQCYBGCZLJMD'],
            self::TYPE['ZZQYZYBGCMD'],
        ),
        IUserGroup::ID['SZGH'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SWMB'] => array(
            self::TYPE['DDMFSBHR'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['WMDW_INFO']
        ),
        IUserGroup::ID['SCZJ'] => array(
            self::TYPE['ZFCGDLJGXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SGSL'] => array(),
        IUserGroup::ID['SLCJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SGGZYJYZX'] => array(),
        IUserGroup::ID['SSJJ'] => array(),
        IUserGroup::ID['SGBDST'] => array(self::TYPE['P_DZDY_INFO'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SGZW'] => array(
            self::TYPE['QYRYXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SFL'] => array(
            self::TYPE['P_YXSBHQS'],
            self::TYPE['P_JGJGBB'],
            self::TYPE['C_SBHQJT'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_JGJGXJJT'],
            self::TYPE['P_JGWMG']
        ),
        IUserGroup::ID['ZFGJJ'] => array(
            self::TYPE['P_GJJDKXX'],
            self::TYPE['C_ZFGJJ'],
            self::TYPE['C_DKJBXX'],
            self::TYPE['P_VWEB_LOAN_INFO'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['GJJGRDKXX'],
            self::TYPE['GJJGRJCXX'],
            self::TYPE['GJJJCXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['GRDKHKMX'],
            self::TYPE['GRJCJCXX'],
            self::TYPE['GRJCMX'],
            self::TYPE['GRMXXX'],
        ),
        IUserGroup::ID['GDGS'] => array(
            self::TYPE['DFJFJL_INFO'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['ZLSGS'] => array(
            self::TYPE['P_WATER_INFO'],
            self::TYPE['P_SFQJXX'],
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
            self::TYPE['C_SFJFJL'],
        ),
        IUserGroup::ID['JSXFY'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['YFXFY'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['YFXZRZRJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['JZQFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['QYQFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['XJXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['THXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['LLXQFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['SBB'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_SYDWNDBG'],
            self::TYPE['C_SYDW_INFO'],
        ),
        IUserGroup::ID['SCXGHJSJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SCRJJCJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SDXGS'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['GAJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SLTGS'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SQXJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_QXZHFYZDDW'],
        ),
        IUserGroup::ID['SRFB'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SSLJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['TSW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['C_JXQNWSJ'],
            self::TYPE['C_QNWMH'],
            self::TYPE['C_QSYXSXDJT'],
            self::TYPE['C_YXQNZYZ'],
            self::TYPE['P_HLJJJY'],
            self::TYPE['P_JASDJCQN'],
            self::TYPE['P_QSYXGQTY'],
            self::TYPE['P_QSYXGQY'],
            self::TYPE['P_QSYXSXDFDY'],
            self::TYPE['P_QSYXSXDY'],
            self::TYPE['P_SDJCQNTM'],
            self::TYPE['P_WSJ'],
            self::TYPE['P_YXQN']
        ),
        IUserGroup::ID['SWXDGLJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SXFZD'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SYDGS'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SHRRQ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['SYCZMJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['SYLBZJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['JGSSFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['JSXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['QAXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['XQXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['YFXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['SCXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['WAXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['AFXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['YXXFGW'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['JKQJFJ'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD'],
            self::TYPE['CCWLJJLXX'],
            self::TYPE['CCWLYQXX'],
        ),
        IUserGroup::ID['SDAG'] => array(
            self::TYPE['DFXBMDXX'],
            self::TYPE['FRHEIMD']
        ),
        IUserGroup::ID['JGQSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['QYQSWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['JSXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['JAXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['XJXSWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['XGXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['GJSWJZJYFXSWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['THXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['SCXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['WAXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['AFXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['YXXSUIWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['JKQSWJ'] => array(
            self::TYPE['NSXX'],
            self::TYPE['QSXX'],
            self::TYPE['FRNSXX'],
            self::TYPE['FRQSXX']
        ),
        IUserGroup::ID['SCXZLSGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['THXZLSGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['XGXZLSGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['JSXGSGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['YFXGSGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['WAXSWJT'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['JAXSWGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['SCXSWJT'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['XJXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['THXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['YFXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['JSXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['YXXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['XGXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['SCXGDGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYDTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
        ),
        IUserGroup::ID['JAXHRRQ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['XGXHTRQ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['YFXHRRQ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['JSXHRRQ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['THXHRRQ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['WAXTRQGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['JGSSTRQGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['YXXTRQGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['SCXTRQGS'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['XJXXARQ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
        ),
        IUserGroup::ID['JKQXZGLJ'] => array(
            self::TYPE['ZRRGYSYJFXX'],
            self::TYPE['ZRRTQGYSYFXX'],
            self::TYPE['FRGYSYJFXX'],
            self::TYPE['FRYDJFXX'],
            self::TYPE['FRYQJFXX'],
            self::TYPE['FRYQTQFXX'],
            self::TYPE['FRYSJFXX'],
            self::TYPE['FRYSTQFXX'],
            self::TYPE['ZRRYDJFXX'],
            self::TYPE['ZRRYDTQFXX'],
            self::TYPE['ZRRYQJFXX'],
            self::TYPE['ZRRYQTQFXX'],
            self::TYPE['ZRRYSJFXX'],
            self::TYPE['ZRRYSTQFXX'],
        ),
        IUserGroup::ID['JKQSHSYJ'] => array(
            self::TYPE['FRTQGYSYFXX'],
            self::TYPE['FRYDTQFXX'],
        ),
        IUserGroup::ID['AFXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['WAXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['YFXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['JSXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['SCXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['QYQMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['THXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['XJXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['XGXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['JGQMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['YXXMZJ'] => array(
            self::TYPE['P_GRDBJFF_INFO']
        ),
        IUserGroup::ID['JSXZFGJJ'] => array(
            self::TYPE['C_DKJBXX'],
            self::TYPE['GRDKHKMX'],
            self::TYPE['GRJCJCXX'],
            self::TYPE['GRJCMX'],
            self::TYPE['GRMXXX'],
            self::TYPE['C_ZFGJJ'],
        ),
        IUserGroup::ID['SCXZFGJJ'] => array(
            self::TYPE['C_DKJBXX'],
            self::TYPE['GRDKHKMX'],
            self::TYPE['GRJCJCXX'],
            self::TYPE['GRJCMX'],
            self::TYPE['GRMXXX'],
            self::TYPE['C_ZFGJJ'],
        ),
        IUserGroup::ID['QYQSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['SCXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['AFXSCJDGLJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['THXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['WAXSGJDGLJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['YXXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['YFXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['XJXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['XGXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['JAXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['JSXSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['JGQSJJ'] => array(
            self::TYPE['GTGSHXX'],
            self::TYPE['QYJBXX'],
        ),
        IUserGroup::ID['YFXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['JKQGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['QYQGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['XJXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['THXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['JSXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['WAXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['AFXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['YXXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['XGXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['JAXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['SCXGAJ'] => array(
            self::TYPE['JASRKJBXX'],
        ),
        IUserGroup::ID['SCXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['JAXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['XGXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['YXXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['JGSSRMFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['AFXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['WAXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['JGQFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['THXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['XJXXFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),
        IUserGroup::ID['QYQFY'] => array(
            self::TYPE['SXBZXRXX'],
            self::TYPE['C_SXBZXJG']
        ),

        //@position_usergroup
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}
